#remote_theme: pages-themes/slate@v0.2.0
remote_theme: aljazceru/midnight-gh-pages-theme
plugins:
- jekyll-remote-theme 

title: Bitcoin Ljubljana
description: Bitcoin Ljubljana meetup
show_downloads: false
google_analytics: G-XDXBJBGBCD
